#!/bin/bash

# Find all .aep files on the computer
find / -name "*.aep" 2>/dev/null | while read file
do
  # Move the file to the "Video Work" folder
  mv "$file" "/Users/Bhavin/Documents/Video Work/"
done

echo "All .aep files have been moved to the Video Work folder."
